Chi-square test
Innopolis-University-Adv-Statistics/Interactive-Statistics-Notebooks pull request #15
Opened 2020-03-31 16:55 UTC by sergey-jr

https://github.com/Innopolis-University-Adv-Statistics/Interactive-Statistics-Notebooks/issues/8

2020-04-11 14:40 UTC, apoyezzhayev reviewed
The notebook uses real-world data and have visualizations. However, there are few issues to pay attention on.  
1) Not convenient to use drop-down for range arguments in `@interact` better to use sliders or text fields
2) No formulas at all. It will be great if at least basic tests be backed with latex math formulas.
3) The information about other chi-squared tests is not present:
  - Chi-squared test for variance in a population distributed normally - important
  - Chi-square test for normality - special case of goodness of fit
  - Binomial test - special case of goodness of fit
  - Reference to Fisher's test 
  - At least links to other tests from wiki using the chi-squared test 
4) There are only two examples and no tasks at all.
5) There are some uncertainties in definitions which should be fixed. 
6) For every hypothesis testing it's better to stick with standard description pipeline like in lectures and labs:
  - Check if assumptions hold
  - Define null and alternative hypothesis
  -  Compute test statistics
  - Compare with table value
  - How to make a decision

2020-04-11 15:06 UTC, apoyezzhayev requested changes

2020-04-11 15:06 UTC, apoyezzhayev commented on Chi_square_test.ipynb
> +        "- A chi-square goodness of fit test determines if a sample data matches a population.\n",
What does this "sample matches population" mean? Some pre-defined distribution?

2020-04-11 15:06 UTC, apoyezzhayev commented on Chi_square_test.ipynb
> +        "- A chi-square goodness of fit test determines if a sample data matches a population.\n",
It's better to add the information that this test has another name - Pearson's chi-squared test

2020-04-11 15:06 UTC, apoyezzhayev commented on Chi_square_test.ipynb
> +        "- A chi-square goodness of fit test determines if a sample data matches a population.\n",
Why there is no any information about assumptions, degrees of freedom and formulas.

2020-04-11 15:06 UTC, apoyezzhayev commented on Chi_square_test.ipynb
> +        "# METADATA\n",
Why do we need it at all? Seems like a copy-paste from the template

2020-04-11 17:42 UTC, sergey-jr commented
@apoyezzhayev 
- [V] Not convenient to use drop-down for range arguments in @interact better to use sliders or text fields
- [added] No formulas at all. It will be great if at least basic tests be backed with latex math formulas. 
- [added] The information about other chi-squared tests is not present

2020-04-11 18:15 UTC, Lehsuby commented
Pros:
- Structure good
- Link to colab
- Nice examples
- Good visualization part

Cons:
- There are **no tasks, self-checking questions**
- The **dependence** of the test on the **number of examples** is not shown
- **Confirmation of a hypothesis** differs from the algorithm that is used in labs

Advices:
- correct spelling mistakes
- add more examples, exercices, self-checking questions
- add examples, which can confirm all statements from the conclusion
- add correct definition of hypothesis

2020-04-11 18:16 UTC, Lehsuby commented on Chi_square_test.ipynb
> +        "We have some sets of data, each of them consisits from ~250 elements. We want to check theitr dictribution. The distributions we wil chick on ot normal, uniform and longnorm."
dictribution, chick

2020-04-11 18:44 UTC, Lehsuby requested changes
Pros:
- Structure good
- Link to colab
- Nice examples
- Good visualization part

Cons:
- There are **no tasks, self-checking questions**
- The **dependence** of the test on the **number of examples** is not shown
- **Confirmation of a hypothesis** differs from the algorithm that is used in labs

Advices:
- correct spelling mistakes
- add more examples, exercises, self-checking questions
- add examples, which can confirm all statements from the conclusion
- add correct definition of hypothesis

2020-04-12 21:35 UTC, sergey-jr commented
@Lehsuby , @apoyezzhayev , @jacked97 please check

2020-04-12 21:45 UTC, Lehsuby requested changes
Cons:

**There are no tasks, self-checking questions**
**Confirmation of a hypothesis** differs from the algorithm that is used in labs

Advices:

**correct spelling mistakes** (comment above)
add exercises, self-checking questions
add correct definition of hypothesis for all exercises

2020-04-12 22:25 UTC, jacked97 approved these changes

2020-04-13 08:02 UTC, sergey-jr commented
@Lehsuby , @apoyezzhayev please check

2020-04-13 08:13 UTC, Lehsuby requested changes
Please, add self-checking questions after examples and exercises

2020-04-13 08:55 UTC, Lehsuby approved these changes
Good, you can add @iteract module for exercises, if you want

2020-04-13 08:58 UTC, sergey-jr commented
@jacked97, @jacked97 please check if all is good.

2020-04-13 09:51 UTC, apoyezzhayev approved these changes

2020-04-13 13:09 UTC, jacked97 approved these changes

2020-04-13 13:09 UTC, merged