Created using Colaboratory
Innopolis-University-Adv-Statistics/Interactive-Statistics-Notebooks pull request #17
Opened 2020-04-02 04:59 UTC by artemkurylev

2020-04-10 15:21 UTC, nikitml requested changes
It's very simple and short, yet I think these fixes are required

1. Remove/Replace/Use the templates, placeholders, and stuff. `<Topic Title>` is to be replaced and all the rest
2. Domain Value Errors should be handled. The scroller for the `p` param of Bernoulli distribution can vary not only for 0..1 
3. I think it's important to provide at least some arguments why this task can be solved using Bernoulli or Binomial distribution etc.
4. I would suggest, that conclusion should be a part, where one could find the to;dr version of the whole notebook, not a statement like "we have learned" :)

2020-04-12 21:19 UTC, lozhn commented
@hamzakpt @ZamiraKholmatova please review

2020-04-12 21:52 UTC, hamzakpt approved these changes

2020-04-13 20:30 UTC, nikitml approved these changes
ok, fine :)

2020-04-13 20:52 UTC, ZamiraKholmatova approved these changes

2020-04-13 20:54 UTC, merged