Initial draft of gamma distribution
Innopolis-University-Adv-Statistics/Interactive-Statistics-Notebooks pull request #20
Opened 2020-04-05 15:17 UTC by sobir-git

2020-04-08 19:37 UTC, sergey-jr reviewed
pros: 
- some interactives
- formulas explained briefly

cons: 
- whole material seems too short
- no link to colab to check how interactive works
- few references (as I think)
- images not working well

All seem like "OK", but if you can change something - do it.

2020-04-10 06:39 UTC, utihamartiwi reviewed
Good explanation about the distribution. For gamma. in properties part, please give space between theta and variance symbol because the first time I saw it I read like : 
mu = k(theta)(sigma^2)=k(theta^2), so I thought mu= k(theta^2)

2020-04-12 21:17 UTC, lozhn commented
@utihamartiwi if everything's fine, please set "approve"
@jacked97  please review
@sobir-git please check comments

2020-04-12 22:24 UTC, jacked97 approved these changes

2020-04-12 22:35 UTC, sobir-git commented
Formulas and images are fixed

2020-04-13 06:33 UTC, sergey-jr requested changes
pros:

- some interactives
- formulas and material explained briefly
- link to colab
cons:
- some characters are broken

2020-04-13 06:37 UTC, sergey-jr commented on gamma-distribution/Gamma_Distribution.ipynb
> +        "Formally, we can parametrize it using shape parameter $k$ and scale $θ$:\n",
Here is a broken character. You can use as you already used ```\\theta```

2020-04-13 09:08 UTC, sergey-jr requested changes
Advice:
- add more examples
- add some tasks
- add some self-questions

2020-04-13 13:15 UTC, sergey-jr approved these changes

2020-04-13 13:27 UTC, utihamartiwi approved these changes

2020-04-13 13:36 UTC, merged