Student t test
Innopolis-University-Adv-Statistics/Interactive-Statistics-Notebooks pull request #21
Opened 2020-04-05 15:25 UTC by jacked97

2020-04-10 19:35 UTC, nikitml requested changes
Hey, so, in general, there's a structure and a part of the topic covered, however, I'd propose to fix these small issues:
1. Explain the assumptions/prerequesites/corener stones about the data you're using
2. I think the interactivity of the charts could address more of the topic and not only the template version of `@interact`
3. Also, I think, you could split the code into smaller parts with a reasoning before the cell and the results of the execution after the cell
4. In the _Conclusion_ part I'd love to have more of a digest/tl;dr version of the whole article, but w/o code. Just, maybe, to refresh the definition (that you have in the first part), remind of the caveats/cornerstones and applicability of the test and so on

Hope you will find no difficulties fixing these issues and will have you work improved dramatically, so the next year students would have a great material to study! Thanks!

2020-04-11 12:57 UTC, apoyezzhayev reviewed
I really liked the section with Pseudo Understanding Of t-Test but the notebook is quite laconic.  
1) Add some visualizations:
 - t-distribution with colored tails
 - t-distribution vs normal distribution for different N
2) Add information about connection between Normal distribution and t-distribution as well as between one-sample t-test and z-test
3) Add some structure for t-test with examples:
  - Paired / Unpaired
  - One sample / two samples location tests
4) Quite interesting intro but is optional (IMHO)

2020-04-11 12:57 UTC, apoyezzhayev commented on Student-T-Test/Student's t-test.ipynb
> +    "! pip install ipywidgets\n",
Split install and import to two different cells for convenient repeated  launch of the notebook.

2020-04-11 12:57 UTC, apoyezzhayev commented on Student-T-Test/Student's t-test.ipynb
> +    "`interact` [documentation](https://ipywidgets.readthedocs.io/en/stable/examples/Using%20Interact.html)"
Why do we need it, it's pretty intuitive

2020-04-11 12:57 UTC, apoyezzhayev commented on Student-T-Test/Student's t-test.ipynb
> +    "lp_variance = liver_patient.var()\n",
Which kind of variance it calculates (biased or not)? Make a remark on it.

2020-04-11 13:01 UTC, apoyezzhayev commented on Student-T-Test/Student's t-test.ipynb
> +    "## Pseduo Understanding Of t-Test\n",
typo: Pseudo

2020-04-12 21:16 UTC, lozhn commented
@jacked97 please check the comments, there's "action required"
@ZamiraKholmatova please review

2020-04-12 22:18 UTC, jacked97 commented
@lozhn & @apoyezzhayev Thanks for the feedback!
@lozhn I have pushed the latest changes based on your review. 
@apoyezzhayev Few things I skipped from your review, since there is another notebook with T-Distribution, so I tried to keep it specific to T-Test.

2020-04-12 22:19 UTC, jacked97 reviewed
Completed in the latest commit

2020-04-12 22:33 UTC, ZamiraKholmatova reviewed
1. Very large intro (it is only my opinion, you can keep it if you like);
2. Some visualizations of distribution will be good (add them => your work will be excellent).

2020-04-13 13:03 UTC, nikitml approved these changes
TOP 👍

2020-04-13 14:06 UTC, apoyezzhayev approved these changes
Good!

2020-04-14 15:11 UTC, ZamiraKholmatova approved these changes

2020-04-14 15:12 UTC, merged