Z-test
Innopolis-University-Adv-Statistics/Interactive-Statistics-Notebooks pull request #26
Opened 2020-04-08 21:19 UTC by hamzakpt

2020-04-10 07:20 UTC, zakariabeni requested changes
HI, 
Actually, I expect more about Z-test because it is what we face in the first time learning about normal distribution. I have some suggestions.
- link to colab.
- you can put some equation related to how to calculated Z.
- put Z table and how to refer the solution in the table.
- display or visualize normal distribution graph based on data.
- in sample task, you used N = 10, but in conclusion you mentioned that Z-test is used for sample size greater than 30. So, it is kind of contradiction.
- you can expand the steps like: after a step there will be a piece of code or explanation. It would be attractive to read.

Thank you.

2020-04-11 12:16 UTC, apoyezzhayev requested changes
Besides comments from review of @zakariabeni 
1) Use latex for math formulas to avoid:
   - x_bar != (not equal) μ.
   - H0
   - σ/sqrt(N), etc.
2) Add or at least describe different use cases for single-tailed tests μ≥μ0 or μ≤μ0
3) At the end of the notebook add one-line z-test from one of python statistical libraries
4) May be add some comments about variance estimation calculation because cases when we definitely know the population's variance are uncommon. It's a nuisance parameters for the test.
5) Add some visualizations for:
   - t-test and z-test comparisons
   - Normal distribution graph with colored tails
6) Add comments that besides one-sample location test there are other applications of Z-test and add references to them
7) Look at some review-comments inside notebook

2020-04-11 12:16 UTC, apoyezzhayev commented on z-test.ipynb
> +    "A Z-test is one of the type of hypothesis test. Hypothesis testing is just a way for you to figure out if results from a test are valid or repeatable. For example, if someone said they had found
"Hypothesis testing is just a way for you to figure out if results from a test are valid or repeatable." - it's not precise definition.

2020-04-11 12:16 UTC, apoyezzhayev commented on z-test.ipynb
> +    "A Z-test is one of the type of hypothesis test. Hypothesis testing is just a way for you to figure out if results from a test are valid or repeatable. For example, if someone said they had found
"Z-test tests the mean of a distribution in which we already know the population variance σ2 " - what does it mean? It's better to say that we test equality of some value to population's mean. Almost always some value is **sample** distribution's mean.

2020-04-11 12:16 UTC, apoyezzhayev commented on z-test.ipynb
> +    "data_sigma = points.std(ddof=0)\n",
Add a comment that usage of ddof=0 is important and why

2020-04-11 12:47 UTC, sergey-jr requested changes
I think same as @apoyezzhayev and @zakariabeni.

2020-04-12 21:14 UTC, lozhn commented
hey @hamzakpt , it's "action required", please take a look

2020-04-13 14:52 UTC, sergey-jr requested changes
Seems like nothing is changed.
- no interaction
- no tasks, questions
- no formulas of Z-test (how to calculate)
- no vizualization
- you don't use latex for equations (that you used)

Overall picture is bad

2020-04-13 21:06 UTC, zakariabeni requested changes
Seem nothing changes, please refer to my first comment.

2020-04-13 21:40 UTC, zakariabeni approved these changes

2020-04-13 21:41 UTC, apoyezzhayev approved these changes

2020-04-13 22:05 UTC, sergey-jr requested changes
Pros:
- formula for z-score
- fixed equation with latex

Cons:
- no interaction at all
- no tasks and self-questions
- no link to colab
- just one example

2020-04-15 09:32 UTC, hamzakpt commented
> Pros:
> 
> * formula for z-score
> * fixed equation with latex
> 
> Cons:
> 
> * no interaction at all
> * no tasks and self-questions
> * no link to colab
> * just one example

included self questions, and provide him colab link. and Interaction provided.

2020-04-15 10:56 UTC, sergey-jr approved these changes

2020-04-15 10:57 UTC, merged